import 'package:qunzo_agent/src/app/navigation/navigation_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/add_money/view/add_money_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/authentication/forgot_password/view/forgot_password_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/authentication/forgot_password/view/sub_sections/forgot_password_pin_verification.dart';
import 'package:qunzo_agent/src/presentation/screens/authentication/forgot_password/view/sub_sections/reset_password.dart';
import 'package:qunzo_agent/src/presentation/screens/authentication/sign_in/view/sign_in_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/authentication/sign_up/view/auth_id_verification/auth_id_verification_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/authentication/sign_up/view/email/email_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/authentication/sign_up/view/personal_info/personal_info_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/authentication/sign_up/view/set_up_password/set_up_password.dart';
import 'package:qunzo_agent/src/presentation/screens/authentication/sign_up/view/sign_up_status/sign_up_status_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/authentication/sign_up/view/verify_email/verify_email_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/authentication/splash/view/splash_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/authentication/two_factor_auth/view/two_factor_auth_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/authentication/welcome/view/welcome_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/cash_in/view/cash_in_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/exchange/view/exchange_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/id_verification/view/id_verification_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/id_verification/view/kyc_history/kyc_history.dart';
import 'package:qunzo_agent/src/presentation/screens/notification/view/notification_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/profit_history/view/profit_history_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/qr_code/view/qr_code_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/settings/view/change_password/change_password.dart';
import 'package:qunzo_agent/src/presentation/screens/settings/view/profile_settings/profile_settings.dart';
import 'package:qunzo_agent/src/presentation/screens/settings/view/settings_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/settings/view/two_fa_authentication/two_fa_authentication.dart';
import 'package:qunzo_agent/src/presentation/screens/support/view/add_new_ticket/add_new_ticket.dart';
import 'package:qunzo_agent/src/presentation/screens/support/view/support_ticket_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/transactions/view/transactions_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/wallets/view/create_new_wallet/create_new_wallet.dart';
import 'package:qunzo_agent/src/presentation/screens/wallets/view/wallet_details/wallet_details.dart';
import 'package:qunzo_agent/src/presentation/screens/wallets/view/wallets_screen.dart';
import 'package:qunzo_agent/src/presentation/screens/withdraw/view/create_withdraw_account/create_withdraw_account.dart';
import 'package:qunzo_agent/src/presentation/screens/withdraw/view/withdraw_screen.dart';
import 'package:qunzo_agent/src/presentation/widgets/maintenance_mode.dart';
import 'package:qunzo_agent/src/presentation/widgets/no_internet_connection.dart';

class RoutesConfig {
  static const splash = SplashScreen();
  static const welcome = WelcomeScreen();
  static const signIn = SignInScreen();
  static const forgotPassword = ForgotPasswordScreen();
  static const forgotPasswordPinVerification = ForgotPasswordPinVerification();
  static const resetPassword = ResetPassword();
  static const email = EmailScreen();
  static const setUpPassword = SetUpPasswordScreen();
  static const personalInfo = PersonalInfoScreen();
  static const authIdVerification = AuthIdVerificationScreen();
  static const verifyEmail = VerifyEmailScreen();
  static const signUpStatus = SignUpStatusScreen();
  static const navigation = NavigationScreen();
  static const twoFactorAuth = TwoFactorAuthScreen();
  static const createNewWallet = CreateNewWallet();
  static const transactions = TransactionsScreen();
  static const wallets = WalletsScreen();
  static const walletsDetails = WalletDetails();
  static const cashIn = CashInScreen();
  static const addMoney = AddMoneyScreen();
  static const withdraw = WithdrawScreen();
  static const createWithdrawAccount = CreateWithdrawAccount();
  static const notification = NotificationScreen();
  static const qrCode = QrCodeScreen();
  static const support = SupportTicketScreen();
  static const addNewTicket = AddNewTicket();
  static const settings = SettingsScreen();
  static const profileSettings = ProfileSettings();
  static const changePassword = ChangePassword();
  static const twoFaAuthentication = TwoFaAuthentication();
  static const idVerification = IdVerificationScreen();
  static const kycHistory = KycHistory();
  static const profitHistory = ProfitHistoryScreen();
  static const noInternetConnection = NoInternetConnection();
  static const exchange = ExchangeScreen();
  static const maintenanceMode = MaintenanceMode();
}
